AfflictedLocals = {
	["ALT + Drag to move the frame anchor."] = "ALT + Drag to move the frame anchor.",
	
	-- Cmd
	["Slash commands"] = "Slash commands",
	["- clear - Clears all running timers."] = "- clear - Clears all running timers.",
	["- ui - Opens the configuration for Afflicted."] = "- ui - Opens the configuration for Afflicted.",
	["- test - Shows test timers in Afflicted."] = "- test - Shows test timers in Afflicted.",
	
	-- GUI
	["General"] = "General",
	
	["None"] = "None",
	["Combat text"] = "Combat text",
	["Party"] = "Party",
	["Raid"] = "Raid",
	["Raid warning"] = "Raid warning",
	["Middle of screen"] = "Middle of screen",
	["Chat frame #%d"] = "Chat frame #%d",

	["Everywhere else"] = "Everywhere else",
	["Battlegrounds"] = "Battlegrounds",
	["Arenas"] = "Arenas",
	["Raid instances"] = "Raid instances",
	["Party instances"] = "Party instances",
	
	["Enable inside"] = "Enable inside",
	
	["Bars"] = "Bars",
	["Icons"] = "Icons",
	
	["Display"] = "Display",
	
	["Font name"] = "Font name",
	["Font size"] = "Font size",
	["Texture"] = "Texture",
	["Width"] = "Width",
	["Only timers of people you have targeted, or focused will be triggered. They will not be removed if you change targets however."] = "Only timers of people you have targeted, or focused will be triggered. They will not be removed if you change targets however.",
	["Only show target/focus timers"] = "Only show target/focus timers",
	["Only show triggered name in text"] = "Only show triggered name in text",
	["Bar only"] = "Bar only",
	["Show timer anchors"] = "Show timer anchors",
	["Show the anchors that lets you drag timer groups around."] = "Show the anchors that lets you drag timer groups around.",
	["Global display setting, changing these will change all the anchors settings.\nNOTE: These values do not reflect each anchors configuration, this is just a quick way to set all of them to the same thing."] = "Global display setting, changing these will change all the anchors settings.\nNOTE: These values do not reflect each anchors configuration, this is just a quick way to set all of them to the same thing.",
	["Grow up"] = "Grow up",
	["Instead of adding everything from top to bottom, timers will be shown from bottom to top."] = "Instead of adding everything from top to bottom, timers will be shown from bottom to top.",
	["Display style"] = "Display style",
	["Scale"] = "Scale",
	["How big the actual timers should be."] = "How big the actual timers should be.",
	["Max timers"] = "Max timers",
	["Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed."] = "Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed.",
	["Configuration that only applies to bar displays."] = "Configuration that only applies to bar displays.",
	["Instead of showing both the spell name and the triggered name, only the name will be shown in the bar."] = "Instead of showing both the spell name and the triggered name, only the name will be shown in the bar.",
	
	["Spells"] = "Spells",
	["Spell categories"] = "Spell categories",
	["Search spells"] = "Search spells",
	
	["All"] = "All",
	
	["Duration disabled"] = "Duration disabled",
	["Duration: %d (%s)"] = "Duration: %d (%s)",
	["Cooldown disabled"] = "Cooldown disabled",
	["Cooldown: %d (%s)"] = "Cooldown: %d (%s)",
	
	["Disable duration"] = "Disable duration",
	["Duration"] = "Duration",
	
	["Disable cooldown"] = "Disable cooldown",
	["Cooldown"] = "Cooldown",
	["Spell cooldown"] = "Spell cooldown",
	["Anchor"] = "Anchor",
	["Spell timer"] = "Spell timer",
	["Spell data"] = "Spell data",
	["Type"] = "Type",
	["Spell type, buffs are things that the player actually gains, casts are anything thats an instant cast spell, summoned objects are things such as totems, and created objects are traps."] = "Spell type, buffs are things that the player actually gains, casts are anything thats an instant cast spell, summoned objects are things such as totems, and created objects are traps.",
	["Casts"] = "Casts",
	["Summoned objects"] = "Summoned objects",
	["Created objects"] = "Created objects",
	["Buffs"] = "Buffs",
	["Class from"] = "Class from",
	["The class that actually casts this spell, used for categorization."] = "The class that actually casts this spell, used for categorization.",
	["Cooldown anchor"] = "Cooldown anchor",
	["Spells linked to this one"] = "Spells linked to this one",
	["Spells that are specifically linked to this one by a spell id. This is basically lower ranked spells, and you only need to set this if you're adding by spell id... and even then you don't really have to."] = "Spells that are specifically linked to this one by a spell id. This is basically lower ranked spells, and you only need to set this if you're adding by spell id... and even then you don't really have to.",
	["Advanced configuration linked to more internal functions.\nValues are separated by commas.\nDO NOT edit these if you do not know what you are doing, you do not have to touch them 99% of the time."] = "Advanced configuration linked to more internal functions.\nValues are separated by commas.\nDO NOT edit these if you do not know what you are doing, you do not have to touch them 99% of the time.",
	["Reset when this is used"] = "Reset when this is used",
	["Spells that should have there cooldown reset when this one is used, think Preparation or Iceblock."] = "Spells that should have there cooldown reset when this one is used, think Preparation or Iceblock.",
	["Advanced"] = "Advanced",
	["Delete"] = "Delete",
	["Spells that were added manually will be deleted, however spells that are added by default are simply reset next update."] = "Spells that were added manually will be deleted, however spells that are added by default are simply reset next update.",
	["Are you REALLY sure you want to delete this spell?"] = "Are you REALLY sure you want to delete this spell?",
	["Add new spell by name or spell id"] = "Add new spell by name or spell id",
	["A spell with that name already exists."] = "A spell with that name already exists.",
	["No spell name entered."] = "No spell name entered.",
	["Add a new spell to Afflicted, you can add it either by the spell name or spell id. However, if you add it by spell name then you must match the casing Blizzard uses as it is case sensitive."] = "Add a new spell to Afflicted, you can add it either by the spell name or spell id. However, if you add it by spell name then you must match the casing Blizzard uses as it is case sensitive.",
	["New spell"] = "New spell",
	["New anchor"] = "New anchor",
	["Anchors"] = "Anchors",
	["Add a new anchor to Afflicted that timers can be displayed in."] = "Add a new anchor to Afflicted that timers can be displayed in.",
	["Anchor name"] = "Anchor name",
	["No anchor name entered."] = "No anchor name entered.",
	["An anchor with that name already exists."] = "An anchor with that name already exists.",

	["Announcement text for when timers are triggered in this anchor. You can use *spell for the spell name, and *target for the person who triggered it (if any)."] = "Announcement text for when timers are triggered in this anchor. You can use *spell for the spell name, and *target for the person who triggered it (if any).",
	["Announce text"] = "Announce text",
	["Destination"] = "Destination",
	["Text color"] = "Text color",
	["Announcements"] = "Announcements",
	["Group name to redirect bars to, this lets you show Afflicted timers under another addons bar group. Requires the bars to be created using GTB, and the bar display to be enabled for this anchor."] = "Group name to redirect bars to, this lets you show Afflicted timers under another addons bar group. Requires the bars to be created using GTB, and the bar display to be enabled for this anchor.",
	["Redirection"] = "Redirection",
	["Fade time"] = "Fade time",
	["How many seconds it should take after a bar is finished for it to fade out."] = "How many seconds it should take after a bar is finished for it to fade out.",
	["Scale"] = "Scale",
	["Icon position"] = "Icon position",
	["Display type"] = "Display type",
	["Enable anchor"] = "Enable anchor",
	["Allows timers to be shown under this anchor, if the anchor is disabled you won't see any timers."] = "Allows timers to be shown under this anchor, if the anchor is disabled you won't see any timers.",
	["Display"] = "Display",
	["Grow up"] = "Grow up",
	["Instead of adding everything from top to bottom, timers will be shown from bottom to top."] = "Instead of adding everything from top to bottom, timers will be shown from bottom to top.",
	["Max timers"] = "Max timers",
	["Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed."] = "Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed.",
	["Redirect bars to group"] = "Redirect bars to group",
	["Enable announcements"] = "Enable announcements",
	["Alert text color, only applies to local outputs."] = "Alert text color, only applies to local outputs.",
	["Start message"] = "Start message",
	["Message to show when a timer is started in this anchor."] = "Message to show when a timer is started in this anchor.",
	["Ended message"] = "Ended message",
	["Message to show when a timer ends inside this anchor."] = "Message to show when a timer ends inside this anchor.",
	["Left"] = "Left",
	["Right"] = "Right",
	["Anchors that were added manually will be deleted, default anchors will be reset to default settings if you delete them. Disable default anchors to stop timers from showing."] = "Anchors that were added manually will be deleted, default anchors will be reset to default settings if you delete them. Disable default anchors to stop timers from showing.",
	["Are you REALLY sure you want to delete this anchor?"] = "Are you REALLY sure you want to delete this anchor?",
	["Move spells in this anchor to"] = "Move spells in this anchor to",
	["You have to choose which anchor spells should be moved to when this one is deleted."] = "You have to choose which anchor spells should be moved to when this one is deleted.",
	
	["Arena spells"] = "Arena spells",
	["2 vs 2"] = "2 vs 2",
	["3 vs 3"] = "3 vs 3",
	["5 vs 5"] = "5 vs 5",
	["Spells that should be enabled inside a specific arena bracket."] = "Spells that should be enabled inside a specific arena bracket.",

	-- Class localization
	["DRUID"] = "Druid",
	["DEATHKNIGHT"] = "Death Knight",
	["WARRIOR"] = "Warrior",
	["PALADIN"] = "Paladin",
	["ROGUE"] = "Rogue",
	["MAGE"] = "Mage",
	["PRIEST"] = "Priest",
	["WARLOCK"] = "Warlock",
	["HUNTER"] = "Hunter",
	["SHAMAN"] = "Shaman",	
}
