-- Translated by wowui.cn

if( GetLocale() ~= "zhCN" ) then
	return
end

AfflictedLocals = setmetatable({

	["ALT + Drag to move the frame anchor."] = "ALT + 拖动 来移动框体锚点.",
	["Reset Afflicted configuration as you were using Afflicted2."] = "重置Afflicted配置当你已使用过Afflicted2.",
	["Interrupted %s"] = "打断 %s",
	["Interrupted %s's %s"] = "打断 %s的 %s",
	["FAILED %s's %s"] = "失败 %s的 %s",
	["Removed %s"] = "移除 %s",
	["Removed %s's %s"] = "移除 %s的 %s",

	-- Cmd
	["Slash commands"] = "Afflicted命令行",
	["- clear - Clears all running timers."] = "- clear - 清除所有运行的计时条.",
	["- ui - Opens the configuration for Afflicted."] = "- ui - 打开Afflicted的配置.",
	["- test - Shows test timers in Afflicted."] = "- test - 显示Afflicted测试计时条.",
	
	-- GUI
	["General"] = "一般选项",
	
	["None"] = "无",
	["Combat text"] = "战斗文本",
	["Party"] = "小队",
	["Raid"] = "团队",
	["Raid warning"] = "团队警报",
	["Middle of screen"] = "屏幕中间",
	["Chat frame #%d"] = "聊天框 #%d",

	["Everywhere else"] = "任何地方",
	["Battlegrounds"] = "战场",
	["Arenas"] = "竞技场",
	["Raid instances"] = "团队副本",
	["Party instances"] = "小队副本",
	
	["Enable inside"] = "在这些情况下启用",
	
	["Bars"] = "计时条",
	["Icons"] = "图标",
	
	["Display"] = "显示选项",
	
	["Font name"] = "字体名字",
	["Font size"] = "字体大小",
	["Texture"] = "材质",
	["Width"] = "宽",
	["Only timers of people you have targeted, or focused will be triggered. They will not be removed if you change targets however."] = "仅有你的已设为目标或焦点的人物将触发计时条.计时条不会因你改变目标而被移除.",
	["Only show target/focus timers"] = "仅显示目标/焦点的计时条",
	["Only show triggered name in text"] = "仅显示触发的名字文本",
	["Bar only"] = "仅显示计时条",
	["Show timer anchors"] = "显示计时条锚点",
	["Show the anchors that lets you drag timer groups around."] = "显示可以拖动计时条分组的锚点.",
	["Global display setting, changing these will change all the anchors settings.\nNOTE: These values do not reflect each anchors configuration, this is just a quick way to set all of them to the same thing."] = "全局显示设置, 更改这些设置将影响到所有锚点的设置.\n注意: 这些选项值不代表是每个锚点的真实配置, 这仅是一个快捷的方式来设置每个锚点为统一的选项值.",
	["Grow up"] = "向上增长",
	["Instead of adding everything from top to bottom, timers will be shown from bottom to top."] = "计时条的显示将从下到上增长而不是从上到下.",
	["Display style"] = "显示样式",
	["Scale"] = "缩放",
	["How big the actual timers should be."] = "设置计时条的大小.",
	["Max timers"] = "最大计时条数量",
	["Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed."] = "每个锚点在同一时间显示的最大计时条数量, 如果同一时间有太多的计时条运行,那么新的计时条将被隐藏直到之前的计时条被移除.",
	["Configuration that only applies to bar displays."] = "仅用来计时条显示的配置.",
	["Instead of showing both the spell name and the triggered name, only the name will be shown in the bar."] = "仅在计时条内显示名字而不是法术名字和触发者的名字.",
	
	["Spells"] = "法术选项",
	["Spell categories"] = "法术分类",
	["Search spells"] = "搜索法术",
	
	["All"] = "所有",
	
	["Duration disabled"] = "持续时间已禁用",
	["Duration: %d (%s)"] = "持续时间: %d (%s)",
	["Cooldown disabled"] = "冷却已禁用",
	["Cooldown: %d (%s)"] = "冷却: %d (%s)",
	
	["Disable duration"] = "禁用持续时间",
	["Duration"] = "持续时间",
	
	["Disable cooldown"] = "禁用冷却",
	["Cooldown"] = "冷却",
	["Spell cooldown"] = "法术冷却",
	["Anchor"] = "锚点",
	["Spell timer"] = "法术计时器",
	["Spell data"] = "法术数据库",
	["Type"] = "类型",
	["Spell type, buffs are things that the player actually gains, casts are anything thats an instant cast spell, summoned objects are things such as totems, and created objects are traps."] = "法术类型, 增益效果为玩家获得的Buff, 可施法的为一个可立即施放的法术, 召唤的物体为类似于图腾等, 制造的物体为类似于陷阱等.",
	["Casts"] = "可施法的",
	["Summoned objects"] = "召唤的物体",
	["Created objects"] = "制造的物体",
	["Buffs"] = "增益效果",
	["Class from"] = "按职业",
	["The class that actually casts this spell, used for categorization."] = "施放这个法术的职业,用做分类.",
	["Cooldown anchor"] = "冷却锚点",
	["Spells linked to this one"] = "法术链接到这个",
	["Spells that are specifically linked to this one by a spell id. This is basically lower ranked spells, and you only need to set this if you're adding by spell id... and even then you don't really have to."] = "特定的按法术ID链接到这一个的法术. 这个基本上是较低等级的法术, 并仅在你按法术ID增加时需要设置这个... and 并且尽管你不是真的必须那么做.",
	["Advanced configuration linked to more internal functions.\nValues are separated by commas.\nDO NOT edit these if you do not know what you are doing, you do not have to touch them 99% of the time."] = "链接到更多内置函数的高级配置.\n数值用逗号分开.\n如果你不知道你在做什么请不要编辑这些参数值, 你有99%的时间不要接触到他们.",
	["Reset when this is used"] = "当这个已被使用时重置",
	["Spells that should have there cooldown reset when this one is used, think Preparation or Iceblock."] = "当这一个法术已用时必须重置冷却的法术, 预先想好或者冻结.",
	["Advanced"] = "高级",
	["Delete"] = "删除",
	["Spells that were added manually will be deleted, however spells that are added by default are simply reset next update."] = "手动增加的法术将被删除, 默认增加的法术将在下次刷新时重置.",
	["Are you REALLY sure you want to delete this spell?"] = "你真的想删除这个法术吗?",
	["Add new spell by name or spell id"] = "增加一个新的法术,按名字或者法术ID.",
	["A spell with that name already exists."] = "这个名字的法术已经存在.",
	["No spell name entered."] = "没有输入法术名字.",
	["Add a new spell to Afflicted, you can add it either by the spell name or spell id. However, if you add it by spell name then you must match the casing Blizzard uses as it is case sensitive."] = "增加一个新的法术到Afflicted, 你可以按照法术名字或者法术ID来增加. 如果你按照法术名字来添加,你必须精确匹配.",
	["New spell"] = "新的法术",
	["New anchor"] = "新的锚点",
	["Anchors"] = "锚点",
	["Add a new anchor to Afflicted that timers can be displayed in."] = "增加一个新的锚点到Afflicted来显示计时器.",
	["Anchor name"] = "锚点名字",
	["No anchor name entered."] = "没有输入锚点名字.",
	["An anchor with that name already exists."] = "锚点名字已存在.",

	["Announcement text for when timers are triggered in this anchor. You can use *spell for the spell name, and *target for the person who triggered it (if any)."] = "当这个锚点下的计时器被触发时的通报文本. 你可以使用 *spell 参数来调用法术名字, 使用 *target 参数来调用谁触发了这个计时器 (如果有的话).",
	["Announce text"] = "通报文本",
	["Destination"] = "通报到",
	["Text color"] = "文本颜色",
	["Announcements"] = "通报",
	["Group name to redirect bars to, this lets you show Afflicted timers under another addons bar group. Requires the bars to be created using GTB, and the bar display to be enabled for this anchor."] = "重定向计时条到的分组名字, 这个可以让你在其他插件的计时条分组下显示Afflicted计时器. 需要这些计时条是使用GTB创建的, 并且在这个锚点下计时条显示已被启用.",
	["Redirection"] = "重定向",
	["Fade time"] = "淡出时间",
	["How many seconds it should take after a bar is finished for it to fade out."] = "一个计时条结束后的淡出秒数.",
	["Scale"] = "缩放",
	["Icon position"] = "图标位置",
	["Display type"] = "显示类型",
	["Enable anchor"] = "启用锚点",
	["Allows timers to be shown under this anchor, if the anchor is disabled you won't see any timers."] = "允许计时器显示在这个锚点下, 如果这个锚点被禁用你将看不到任何计时器.",
	["Display"] = "显示",
	["Grow up"] = "向上增长",
	["Instead of adding everything from top to bottom, timers will be shown from bottom to top."] = "计时条的显示将从下到上增长而不是从上到下.",
	["Max timers"] = "最大计时条数量",
	["Maximum amount of timers that should be ran per an anchor at the same time, if too many are running at the same time then the new ones will simply be hidden until older ones are removed."] = "每个锚点在同一时间显示的最大计时条数量, 如果同一时间有太多的计时条运行,那么新的计时条将被隐藏直到之前的计时条被移除.",
	["Redirect bars to group"] = "重定向计时条到分组",
	["Enable announcements"] = "启用通报",
	["Alert text color, only applies to local outputs."] = "警报文本的颜色, 仅用来本地输出.",
	["Start message"] = "计时开始的信息",
	["Message to show when a timer is started in this anchor."] = "当这个锚点下的计时器开始计时时的信息.",
	["Ended message"] = "计时结束的信息",
	["Message to show when a timer ends inside this anchor."] = "当这个锚点下的计时器结束计时时的信息.",
	["Left"] = "左",
	["Right"] = "右",
	["Anchors that were added manually will be deleted, default anchors will be reset to default settings if you delete them. Disable default anchors to stop timers from showing."] = "手动增加的锚点将被删除, 默认的锚点将被重置为默认设置如果你删除他们的话. 禁用默认锚点来阻止计时条的显示.",
	["Are you REALLY sure you want to delete this anchor?"] = "你真的想删除这个锚点?",
	["Move spells in this anchor to"] = "移动这个锚点里的法术到",
	["You have to choose which anchor spells should be moved to when this one is deleted."] = "当这个锚点被删除后你必须选择一个法术要移动到的锚点.",
	
	["Arena spells"] = "竞技场法术",
	["2 vs 2"] = "2 vs 2",
	["3 vs 3"] = "3 vs 3",
	["5 vs 5"] = "5 vs 5",
	["Spells that should be enabled inside a specific arena bracket."] = "需要在不同竞技场启用的法术.",

	["Announcements"] = "通报",
	["Color"] = "颜色",
	["Dispel announcements"] = "驱散通报",
	["Interrupt announcements"] = "打断通报",

	-- Class localization
	["DRUID"] = "德鲁伊",
	["DEATHKNIGHT"] = "死亡骑士",
	["WARRIOR"] = "战士",
	["PALADIN"] = "圣骑士",
	["ROGUE"] = "潜行者",
	["MAGE"] = "法师",
	["PRIEST"] = "牧师",
	["WARLOCK"] = "术士",
	["HUNTER"] = "猎人",
	["SHAMAN"] = "萨满",	

}, {__index = AfflictedLocals})